CREATE DATABASE IF NOT EXISTS points;
USE points;
DROP TABLE IF EXISTS out_s3;
DROP TABLE IF EXISTS out_s4;
set hive.cli.print.header=true;
CREATE TABLE out_s3 (SN STRING, x STRING, y STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' stored as textfile;
CREATE TABLE out_s4 (SN STRING, x STRING, y STRING) ROW FORMAT DELIMITED FIELDS TERMINATED BY ',' stored as textfile;
LOAD DATA LOCAL INPATH '../output_files/out_s2.csv' OVERWRITE INTO TABLE points.out_s3;
SELECT * FROM out_s3 WHERE x IS NULL LIMIT 10;
