USE char_rec;
DROP TABLE IF EXISTS out_s4;
CREATE TABLE out_s4 (SN VARCHAR(10), x VARCHAR(10), y VARCHAR(10));
INSERT INTO out_s4 SELECT * FROM out_s3 WHERE x IS NOT NULL AND y is NOT NULL;
SELECT * FROM out_s4 LIMIT 10;
